
# Name of the workflow shown in GitHub Actions
name: DevSecOps Pipeline


permissions:
  # Allows the workflow to read repository contents (code, files)
  contents: read
  
  # Allows security tools (like CodeQL) to upload vulnerability results
  # to GitHub's Security tab (code scanning alerts) 

  security-events: write



# Force GitHub Actions to use Node.js 24 (future-proof)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


# Trigger the workflow on push or pull request
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:


# Define jobs
jobs:
  test:

    # Use a Linux virtual machine
    runs-on: ubuntu-latest

    steps:

    # Step 1 : Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # fetch full git history


   
    - name: Show commit information
      run: |
        echo "Triggered by: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"

    
    # Step : Scan for secrets in code
    - name: Scan for secrets (Gitleaks)
      uses: gitleaks/gitleaks-action@v2



    # Step : Install Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Step : Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step : Dependency vulnerability scan (SCA)

    - name: Run dependency scan (pip-audit)
      run: |
        pip install pip-audit
        echo "Running dependency scan..."
        pip-audit || true


    
    # Generate SBOM (Software Bill of Materials)
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        path: .
        format: spdx-json

    
    # Upload SBOM as artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.spdx.json

    
    # Step : Lint code (static code analysis)
    - name: Run linting (flake8)
      run: |
        # Fail on syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # Report warnings (does not fail pipeline)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    # Step : Run tests
    - name: Run tests
      run: pytest



  #  Job 2: Code scanning (SAST)
  codeql:

    name: CodeQL Analysis

    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Run CodeQL analysis
    - name: Analyze code
      uses: github/codeql-action/analyze@v3

